DROP TABLE IF EXISTS `Product`;
CREATE TABLE IF NOT EXISTS `Product` (
	`product_id` BIGINT(20) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`name` VARCHAR(200) NOT NULL,
    `description` TEXT NOT NULL,
	`model` VARCHAR(200) NOT NULL,
    `price` NUMERIC (10,2) NOT NULL,
	`category_id` BIGINT(20) NOT NULL,
    `created_on` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `modified_on` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	FOREIGN KEY fk_category (`category_id`)
	REFERENCES `Category` (`category_id`)
	ON UPDATE CASCADE
	ON DELETE RESTRICT
);
