DROP TABLE IF EXISTS `Category`;
CREATE TABLE IF NOT EXISTS `Category` (
    `id` INTEGER PRIMARY KEY,
    `name` TEXT NOT NULL UNIQUE,
    `description` TEXT NOT NULL,
    `created_on` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `modified_on` DATETIME DEFAULT CURRENT_TIMESTAMP
);