CREATE TABLE IF NOT EXISTS `Product` (
	`product_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(200) NOT NULL,
    `description` TEXT NOT NULL,
	`category` VARCHAR(200) NOT NULL,
	`model` VARCHAR(200) NOT NULL,
    `price` NUMERIC (10,2) NOT NULL,
    `created_on` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `modified_on` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`product_id`)
);
